# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remarks',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(db_index=True, max_length=14, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=512),
        ),
    ]
