# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20161202_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField(max_length=20000)),
                ('audio', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='owner',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='collide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='diffusion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='nb_max',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='event',
            name='participation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_until',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='event',
            name='subjects_distribution_date',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Subject'),
        ),
    ]
