# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170331_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='website.Locutor'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='website.Locutor'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
