# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170427_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_open',
            field=models.BooleanField(default=False),
        ),
    ]
