# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170427_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech', to='website.Subject'),
        ),
    ]
