# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170427_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='id',
            field=models.CharField(db_index=True, max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
