# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170427_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='locutor',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
