# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_locutor_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=5),
        ),
    ]
